plugins:
  site_activity_enabled:
    default: true
    client: true
  site_activity_group:
    default: "admins"
  site_activity_member_online_minute:
    default: 10080
    min: 1
  site_activity_group_online_minute:
    default: 10080
    min: 1
  site_activity_guest_online_day:
    default: 7
    min: 1
